export const TOKENS = {
  cantera: {
    name: 'Cantera',
    primary: '#0E5A3D',
    primaryDark: '#083D29',
    primarySoft: '#E8F2EC',
    accent: '#F26B1D',
    accentDark: '#C4530F',
    accentSoft: '#FFE9D8',
    warn: '#E5B100',
    danger: '#C8371A',
    ok: '#1F7A3B',
    ink: '#0F1A17',
    ink2: '#3B4A44',
    ink3: '#67746F',
    line: '#DCE4DF',
    line2: '#E9EDEA',
    bg: '#F6F8F5',
    bgAlt: '#FFFFFF',
    surface: '#FFFFFF',
    chip: '#F0EFE8',
    display: "'Archivo', 'Inter', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
  },
  volquete: {
    name: 'Volquete',
    primary: '#111111',
    primaryDark: '#000000',
    primarySoft: '#F1F1F0',
    accent: '#FFCC00',
    accentDark: '#D9A900',
    accentSoft: '#FFF6CC',
    warn: '#F26B1D',
    danger: '#C8371A',
    ok: '#1F7A3B',
    ink: '#0A0A0A',
    ink2: '#2E2E2E',
    ink3: '#6A6A6A',
    line: '#E0E0DE',
    line2: '#EDEDEC',
    bg: '#FAFAF7',
    bgAlt: '#FFFFFF',
    surface: '#FFFFFF',
    chip: '#F1F1EC',
    display: "'Archivo', 'Inter', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
  },
  arena: {
    name: 'Arena',
    primary: '#1F2933',
    primaryDark: '#0F1620',
    primarySoft: '#ECEFF2',
    accent: '#C44A1E',
    accentDark: '#9B3A17',
    accentSoft: '#FCE6DB',
    warn: '#D9A800',
    danger: '#B12E18',
    ok: '#3A7A4B',
    ink: '#1B1D1F',
    ink2: '#3F454A',
    ink3: '#6E7579',
    line: '#E2DACF',
    line2: '#F0EBE0',
    bg: '#F5EEE1',
    bgAlt: '#FBF7EE',
    surface: '#FFFFFF',
    chip: '#EEE5D4',
    display: "'Archivo', 'Inter', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
  },
};
